version: '3.8'

services:
  gateway:
    build: gateway/
    image: benito/shareit-gateway:v1
    container_name: shareit-gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  server:
    build: server/
    image: benito/shareit-server:v1
    container_name: shareit-server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  db:
    image: postgres:13.7-alpine
    container_name: shareit-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime